### ISSUE TITLE
Feature: Add CloudWatch

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/terraform-aws-vault#32]
It would be nice to allow users to enable [CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html).

When enabled: (likely a variable: `cloudwatch_enabled` (bool))
- [x] Install a package, configure and start cloud watch.
- [x] (nice to have) Have Terraform create a Dashboard for Vault.
- [x] (nice to have) Add alerting. (Interesting to look at memory usage)
- [x] (nice to have) Send logs to AWS. (logs: `journalctl` and/or audit logs.)

**Comment by repping** [comment]
Enabling Cloudwatch will now send the journalctl logs and cloudinit logs to "Cloudwatch logs". How do you like the current implementation? I was thinking it might be nice to be able to enable/disable Cloudwatch metrics and logs separately, what do you think?

I will look at audit logging next and alerting after that.
