### ISSUE TITLE
Bug: Using a `vault_data_path` other then the default "/opt/vault" causes provisioning to fail.

### ISSUE THREAD

**Issue by repping** [robertdebock/terraform-aws-vault#44]
The vault rpm installed uses `/opt/vault` as the default installation path, this is the same as the default value for the terraform variable `vault_data_path`. Because of this the provisioning completes succesfully.

When using a non-default `vault_data_path` we also need a folder called `data` to be created in this location.
This was not a problem before as the RPM would create it. With a non-default `vault_data_path` we need to create it during provisioning.

My suggestion is to add the following code to the userdata script:
```bash
# Create and configure the Vault data folder when it is different from the default path created by the rpm.
if [ "${vault_data_path}" != "/opt/vault" ] ; then
  mkdir ${vault_data_path}/data
  chown vault:vault ${vault_data_path}/data
  chmod 755 ${vault_data_path}/data
fi
```

**Comment by robertdebock** [comment]
Fixed (yourself ;-) ) with version [10.1.4](https://github.com/robertdebock/terraform-aws-vault/releases/tag/10.1.4). Thanks!
