### ISSUE TITLE
Cloudwatch alarms an log-groups arent being cleanup up properly after terraform destroy

### ISSUE THREAD

**Issue by repping** [robertdebock/terraform-aws-vault#64]
1. Cloudwatch alarms are not cleaned up after terraform destroy. They do seem to be getting cleaned up as expected in any other situation.
2. Cloudwatch log-groups "cldwt-vaultlog", "cldwt-cloudinitlog" and "/aws/lambda/CloudWatchAutoAlarms-zuikyd" have their retention set to "never expire". This should be something like 7 days so no junk is left behind.

**Comment by robertdebock** [comment]
I noticed that too, if you can have a look, please.
