### ISSUE TITLE
Instances differ in size.

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/terraform-aws-vault#71]
The AWS Autoscaling group now selects instances based on:

- `vault_asg_minimum_required_memory`
- `vault_asg_minimum_required_vcpus`

This may lead to an auto-scaling group, that has different sized instances.

**Comment by robertdebock** [comment]
Confirmed, but this is intended behaviour.

By setting the minima for CPU and Memory, we basically request the smallest instance available. When such an instance is not available, an alternative (likely a bit bigger) will be selected.

In other words, when you would "hard-code" an instance size, the deployment would fail rather than selecting a different size.

Hope this explains this behaviour, I'll close the issue.

**Comment by koen-venly** [comment]
Hi Robert,

Yes... We know... But we would prefer to just be able to choose the instances... Can't this be bot implemented using some sort of if structure?
Something like
If instance_size is choosen, use that otherwise the other 2 vars are needeed?
