### ISSUE TITLE
Deployments lead to http status `501` on Vault nodes.

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/terraform-aws-vault#72]
In the target group, nodes report `unhealthy` with status 501.

**Comment by robertdebock** [comment]
That's correct, after deploying, the Vault cluster is not initialised and will return [501](https://developer.hashicorp.com/vault/api-docs/system/health). 

This behaviour is described in the [READMD.md](https://github.com/robertdebock/terraform-aws-vault#deployment) and displayed as `output` when running the module:

```hcl
instructions = <<EOT
  1. Run: ssh ec2-user@YOU_BASTION_HOST
  2. Run: vault operator init
  3. Run: vault login
  4. Run: vault operator raft autopilot set-config -min-quorum=3 -cleanup-dead-servers=true -dead-server-last-contact-threshold=120
```

Hope that explains the situation.

**Comment by koen-venly** [comment]
Yes,
But when you are using the bastion host of vault as centralized management instance, you will never be able to run those commands. Because the load balancer will kill the unhealthy host
